#!/bin/bash

BUILD_DIR="$(pwd)"
LUA_SCRIPT="$BUILD_DIR/watch.lua"
BUILD_TXT="$BUILD_DIR/lbuild.txt"

if [ "$1" == "--setup" ]; then
    echo "[LCW::SETUP] Creating build directory and default config..."
    mkdir -p "$BUILD_DIR"

    cp /usr/local/share/lcw/setup/watch.lua "$LUA_SCRIPT"

    if [ ! -f "$BUILD_TXT" ]; then
        echo "gcc *.c -o out -Wall" > "$BUILD_TXT"
    fi

    echo "[LCW::SETUP] Setup finished!"
    exit 0
fi

if [ -z "$1" ]; then
    echo "[LCW::ERROR] Expected project directory argument"
    echo "Usage: lcw <project_dir>"
    exit 1
fi

PROJECT_DIR="$1"

echo "[LCW::INIT] Starting watcher..."

lua "$LUA_SCRIPT" "$PROJECT_DIR"

